#!/usr/bin/env python
"""capabilities/color/luts/_generate-luts.py — generate the house-LUT library.

We GENERATE our own .cube LUTs deterministically (math documented below) rather than shipping
license-encumbered third-party packs. Drop-in external .cube files (FreeLUTs.net / RocketStock free
packs) also work with color/grade.ts — this just gives a clean, reproducible, license-free baseline.

Run once (venv python): capabilities/.venv/{Scripts-or-bin}/python capabilities/color/luts/_generate-luts.py
Produces (size-33 Adobe .cube, red-fastest order):
  neutral-correct.cube  — gentle S-curve contrast, neutral WB (safe baseline / "correct")
  warm-cine.cube        — warm WB (R up / B down) + soft contrast (warm cinematic look)
  teal-orange.cube      — shadows -> teal, highlights -> orange (cinematic)
  film-kodak2383.cube    — faded blacks + warm highs + slight desaturation (film emulation)
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

SIZE = 33
HERE = Path(__file__).resolve().parent


def _grid() -> np.ndarray:
    """(SIZE^3, 3) array of input RGB in [0,1], RED FASTEST (Adobe .cube order: b outer, g mid, r inner)."""
    axis = np.linspace(0.0, 1.0, SIZE)
    b, g, r = np.meshgrid(axis, axis, axis, indexing="ij")
    return np.stack([r.ravel(), g.ravel(), b.ravel()], axis=1)


def _scurve(x: np.ndarray, amount: float) -> np.ndarray:
    """Gentle contrast S-curve around 0.5. amount 0 = identity."""
    return np.clip(x + amount * np.sin((x - 0.5) * np.pi) * 0.5, 0.0, 1.0)


def neutral_correct(rgb: np.ndarray) -> np.ndarray:
    return _scurve(rgb, 0.12)


def warm_cine(rgb: np.ndarray) -> np.ndarray:
    out = _scurve(rgb, 0.10).copy()
    out[:, 0] = np.clip(out[:, 0] * 1.06 + 0.01, 0, 1)   # R up
    out[:, 2] = np.clip(out[:, 2] * 0.94, 0, 1)          # B down
    return out


def teal_orange(rgb: np.ndarray) -> np.ndarray:
    out = _scurve(rgb, 0.15).copy()
    luma = (0.2126 * out[:, 0] + 0.7152 * out[:, 1] + 0.0722 * out[:, 2])[:, None]
    shadows = np.clip(1.0 - luma * 2.0, 0, 1)      # weight in darks
    highs = np.clip(luma * 2.0 - 1.0, 0, 1)        # weight in brights
    out[:, 1] += shadows[:, 0] * 0.04              # teal = G+B in shadows
    out[:, 2] += shadows[:, 0] * 0.06
    out[:, 0] += highs[:, 0] * 0.06                # orange = R up, B down in highs
    out[:, 2] -= highs[:, 0] * 0.04
    return np.clip(out, 0, 1)


def film_kodak2383(rgb: np.ndarray) -> np.ndarray:
    out = rgb.copy()
    out = 0.04 + out * 0.92                          # lift blacks, lower whites (faded)
    out = _scurve(out, 0.08)
    mean = out.mean(axis=1, keepdims=True)
    out = mean + (out - mean) * 0.92                 # slight desaturation
    out[:, 0] = np.clip(out[:, 0] * 1.03, 0, 1)      # warm highs
    out[:, 2] = np.clip(out[:, 2] * 0.97, 0, 1)
    return np.clip(out, 0, 1)


def write_cube(name: str, title: str, data: np.ndarray) -> None:
    lines = [f"# house LUT — {title} (generated by _generate-luts.py)",
             f'TITLE "{title}"', f"LUT_3D_SIZE {SIZE}", "DOMAIN_MIN 0.0 0.0 0.0", "DOMAIN_MAX 1.0 1.0 1.0", ""]
    lines += [f"{r:.6f} {g:.6f} {b:.6f}" for r, g, b in data]
    (HERE / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {name} ({len(data)} entries)")


if __name__ == "__main__":
    grid = _grid()
    write_cube("neutral-correct.cube", "Neutral Correct", neutral_correct(grid))
    write_cube("warm-cine.cube", "Warm Cine", warm_cine(grid))
    write_cube("teal-orange.cube", "Teal-Orange", teal_orange(grid))
    write_cube("film-kodak2383.cube", "Film Kodak 2383", film_kodak2383(grid))
